---
title: "About the notes"
output:
  html_document:
    toc: true
---

On this site you find some notes I took over the last years on quite diverse topics. Some of the notes are well worked out. Others are unfinished or work in progress and may contain errors. Most notes are in English, some are written in German. Notes which I considered useful for a broader audience are also published on my [R you ready](http://ryouready.wordpress.com) blog.

All the source code to produce the notes can be found in one of the folders of the master branch of [this github repository](https://github.com/markheckmann/notes). 

* R

* Stats
    + [Cross Validation](./cross_validation.html)
    + [Regression: Testing custom hypothesis](./regression_custom_hypotheses.html)
    + [QQ-plots in R vs SPSS](./qq_plot_by_hand.html)
    
* Methods 
    + [Thurstone Skalierung](./scaling_thurstone.html)
    
* Linear algebra
    + TODO

* Papers redone in R
    + [Tarakci et al. (2014). Strategic consensus mapping](./strategic_consensus_mapping_sray.html)
    + [Abdi & Valentin (2007). Multiple factor analysis (MFA)](./multiple_factor_analysis.html)
    
    

